apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image: adnandiu31/node-web-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
